Update selector documentation.
AvaloniaUI/Documentation pull request #345
Opened 2022-10-09 06:17 UTC by rabbitism

1. move quote blocks to hints. 
2. Specify that Properties in PropertyEquals selector must have associated TypeConverter. 
3. Add detailed syntax and samples for nth-child and nth-last-child selector.

2022-10-09 18:36 UTC, jmacato requested changes

2022-10-09 18:36 UTC, jmacato commented on docs/styling/selectors.md
> +**Note:** When using a `AttachedProperty` in selectors inside XAML, it has to be wrapped in braces.
```suggestion
**Note:** When using a `AttachedProperty` in selectors inside XAML, it has to be wrapped in parenthesis.
```

2022-10-10 01:42 UTC, rabbitism commented on docs/styling/selectors.md
> +**Note:** When using a `AttachedProperty` in selectors inside XAML, it has to be wrapped in braces.
Updated, thanks for the review.

2022-10-10 01:46 UTC, maxkatz6 approved these changes

2022-10-10 01:46 UTC, merged